name: deploy to ${{vars.ENV_NAME}} env
on:
  push:
    branches:
      - 'develop'
env:
  env_name: ${{vars.ENV_NAME}}
jobs:
  build:
    uses: ./.github/workflows/docker-image.yml
  deploy-dev:
    runs-on: ubuntu-latest
    environment: ${{vars.ENV_NAME}}
    needs: [build]
    steps:
      - name: download artifact
        run: echo "downloading artifact"
      - name: deploying 
        run: echo "deploying to ${{vars.ENV_NAME}} env"
