name: deploy 
on:
  push:
    branches:
      - 'develop'
env:
  env_name: ${{ vars.ENV_NAME }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  
jobs:
  build:
    uses: ./.github/workflows/docker-image.yml
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    needs: [build]
    steps:
      - name: download artifact
        run: echo "downloading artifact"
      - name: deploying 
        run: echo "deploying to $env_name env"
