name: deploy 
on:
  push:
    branches:
      - 'develop'
jobs:
  build:
    uses: ./.github/workflows/docker-image.yml
  deploy-dev:
    runs-on: ubuntu-latest
    env:
      env_name: '${{ env.ENV_NAME }}'
    environment: $env_name
    needs: [build]
    steps:
      - name: download artifact
        run: echo "downloading artifact"
      - name: deploying 
        run: echo "deploying to $env_name env"
