name: Docker Image CI

on: 
  workflow_call:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  
 # deploy-dev:
 #   runs-on: ubuntu-latest
 #   needs: build
 #   environment: dev
 #   steps:
 #     - name: download artifact
 #       run: echo "downloading artifact"
 #     - name: deploying 
 #       run: echo "deploying to dev env"
        
 # deploy-qa:
  #  runs-on: ubuntu-latest
   # environment: qa
   # needs: [build, deploy-dev]
   # steps:
    #  - name: download artifact
    #    run: echo "downloading artifact"
    #  - name: deploying 
    #    run: echo "deploying to dev env"
        
        
  
        
        
        
